### ISSUE TITLE
프로젝트 이름..?

### ISSUE THREAD

**Issue by makemyway-kr** [amuguna1mandeum/gomin-sageori#1]
뭐로하지....?

**Comment by unbroken2650** [comment]
MatZipChuCheon

MZCC

MZ세대를 겨냥해봤습니다.

**Comment by makemyway-kr** [comment]
우리 이름도 어떻게 해야할듯 그러고보니까 ㅋㅋㅋ

2022년 3월 1일 (화) 오후 11:15, UnbroKen ***@***.***>님이 작성:

**Comment by makemyway-kr** [comment]
Mzcc....굿 아이디어 랄까....?

2022년 3월 1일 (화) 오후 11:18, WonJun Sim ***@***.***>님이 작성:
